project: default
source:
  repoURL: 'https://github.com/mehmetmgrsl/helm-chart-nginx.git'
  path: .
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true